### ISSUE TITLE
Add support for file uploads

### ISSUE THREAD

**Issue by cobusc** [praekelt/swagger-django-generator#3]
https://swagger.io/docs/specification/2-0/file-upload/

Swagger makes provision for uploading files using form data:
```yml
paths:
   /upload:
     post:
       summary: Uploads a file.
       consumes:
         - multipart/form-data
       parameters:
         - in: formData
           name: upfile
           type: file
           description: The file to upload.
```
Currently `in: formData` is not supported in this tool.
Files are available in the `request.FILES` dictionary in Django.
